local palette = require("vault.palette").colors
local config = require("vault.config")

---Get plugin highlight groups
---@return table<string, vim.api.keyset.highlight>
local function get()
  local p = palette
  local transparent = config.transparent

  local bg       = transparent and p.none or p.bg
  local bg_float = transparent and p.none or p.ui_bg

  return {
    -- Telescope
    TelescopeNormal         = { fg = p.fg,      bg = bg_float },
    TelescopeBorder         = { fg = p.comment, bg = bg_float },
    TelescopeTitle          = { fg = p.fg,      bold = true },
    TelescopePromptNormal   = { fg = p.fg,      bg = bg_float },
    TelescopePromptBorder   = { fg = p.comment, bg = bg_float },
    TelescopePromptTitle    = { fg = p.fg,      bg = bg_float, bold = true },
    TelescopePromptPrefix   = { fg = p.fg },
    TelescopePromptCounter  = { fg = p.comment },
    TelescopeResultsNormal  = { fg = p.fg,      bg = bg_float },
    TelescopeResultsBorder  = { fg = p.comment, bg = bg_float },
    TelescopeResultsTitle   = { fg = p.comment, bg = bg_float },
    TelescopePreviewNormal  = { fg = p.fg,      bg = bg_float },
    TelescopePreviewBorder  = { fg = p.comment, bg = bg_float },
    TelescopePreviewTitle   = { fg = p.comment, bg = bg_float },
    TelescopePreviewLine    = { bg = p.selection },
    TelescopeSelection      = { bg = p.selection },
    TelescopeSelectionCaret = { fg = p.green,   bg = p.selection },
    TelescopeMultiSelection = { bg = p.selection },
    TelescopeMultiIcon      = { fg = p.fg },
    TelescopeMatching       = { fg = p.green,   bold = true },

    -- FzfLua
    FzfLuaNormal           = { fg = p.fg,      bg = bg_float },
    FzfLuaBorder           = { fg = p.comment, bg = bg_float },
    FzfLuaTitle            = { fg = p.fg,      bold = true },
    FzfLuaCursor           = { link = "Cursor" },
    FzfLuaSearch           = { link = "IncSearch" },
    FzfLuaCursorLine       = { bg = p.selection },
    FzfLuaCursorLineNr     = { fg = p.fg,      bg = p.selection },
    FzfLuaScrollFloatEmpty = { bg = p.ui_bg },
    FzfLuaScrollFloatFull  = { bg = p.comment },
    FzfLuaPreviewNormal    = { fg = p.fg,      bg = bg_float },
    FzfLuaPreviewBorder    = { fg = p.comment, bg = bg_float },
    FzfLuaPreviewTitle     = { fg = p.fg,      bold = true },

    -- Neo-tree
    NeoTreeNormal             = { fg = p.fg,      bg = bg },
    NeoTreeNormalNC           = { fg = p.fg,      bg = bg },
    NeoTreeVertSplit          = { fg = p.comment, bg = bg },
    NeoTreeWinSeparator       = { fg = p.comment, bg = bg },
    NeoTreeEndOfBuffer        = { fg = bg,        bg = bg },
    NeoTreeSignColumn         = { bg = bg },
    NeoTreeRootName           = { fg = p.green,   bold = true },
    NeoTreeGitAdded           = { fg = p.green },
    NeoTreeGitDeleted         = { fg = p.error },
    NeoTreeGitModified        = { fg = p.warning },
    NeoTreeGitConflict        = { fg = p.error,   bold = true },
    NeoTreeGitUntracked       = { fg = p.comment },
    NeoTreeGitIgnored         = { fg = p.comment },
    NeoTreeGitRenamed         = { fg = p.green },
    NeoTreeGitStaged          = { fg = p.green },
    NeoTreeGitUnstaged        = { fg = p.warning },
    NeoTreeIndentMarker       = { fg = p.comment },
    NeoTreeExpander           = { fg = p.fg },
    NeoTreeFileIcon           = { fg = p.fg },
    NeoTreeFileName           = { fg = p.fg },
    NeoTreeFileNameOpened     = { fg = p.fg,      bold = true },
    NeoTreeDirectoryIcon      = { fg = p.green },
    NeoTreeDirectoryName      = { fg = p.green },
    NeoTreeSymbolicLinkTarget = { fg = p.string },
    NeoTreeDotfile            = { fg = p.comment },
    NeoTreeFloatBorder        = { fg = p.comment, bg = bg_float },
    NeoTreeFloatNormal        = { fg = p.fg,      bg = bg_float },
    NeoTreeFloatTitle         = { fg = p.green,   bg = bg_float },
    NeoTreeTitleBar           = { fg = p.green,   bg = bg_float },
    NeoTreeCursorLine         = { bg = p.selection },

    -- nvim-tree
    NvimTreeNormal           = { fg = p.fg,      bg = bg },
    NvimTreeNormalNC         = { fg = p.fg,      bg = bg },
    NvimTreeVertSplit        = { fg = p.comment, bg = bg },
    NvimTreeWinSeparator     = { fg = p.comment, bg = bg },
    NvimTreeEndOfBuffer      = { fg = bg,        bg = bg },
    NvimTreeRootFolder       = { fg = p.green,   bold = true },
    NvimTreeGitDirty         = { fg = p.warning },
    NvimTreeGitNew           = { fg = p.green },
    NvimTreeGitDeleted       = { fg = p.error },
    NvimTreeGitMerge         = { fg = p.warning },
    NvimTreeGitRenamed       = { fg = p.green },
    NvimTreeGitStaged        = { fg = p.green },
    NvimTreeGitIgnored       = { fg = p.comment },
    NvimTreeIndentMarker     = { fg = p.comment },
    NvimTreeFolderIcon       = { fg = p.green },
    NvimTreeFolderName       = { fg = p.green },
    NvimTreeOpenedFolderName = { fg = p.green,   bold = true },
    NvimTreeEmptyFolderName  = { fg = p.comment },
    NvimTreeSymlink          = { fg = p.string },
    NvimTreeSpecialFile      = { fg = p.fg },
    NvimTreeImageFile        = { fg = p.warning },

    -- GitSigns
    GitSignsAdd              = { fg = p.green },
    GitSignsChange           = { fg = p.fg },
    GitSignsDelete           = { fg = p.error },
    GitSignsAddNr            = { fg = p.green },
    GitSignsChangeNr         = { fg = p.fg },
    GitSignsDeleteNr         = { fg = p.error },
    GitSignsAddLn            = { bg = p.git_add_bg },
    GitSignsChangeLn         = { bg = p.git_change_bg },
    GitSignsDeleteLn         = { bg = p.git_delete_bg },
    GitSignsAddInline        = { fg = p.green },
    GitSignsChangeInline     = { fg = p.fg },
    GitSignsDeleteInline     = { fg = p.error },
    GitSignsCurrentLineBlame = { fg = p.comment },
    GitSignsChangedelete     = { fg = p.warning },
    GitSignsTopdelete        = { fg = p.error },
    GitSignsUntracked        = { fg = p.comment },
    GitSignsStagedAdd        = { fg = p.green },
    GitSignsStagedChange     = { fg = p.comment },
    GitSignsStagedDelete     = { fg = p.error },

    -- Indent Blankline (legacy + ibl v3)
    IndentBlanklineChar               = { fg = p.comment, nocombine = true },
    IndentBlanklineSpaceChar          = { fg = p.comment, nocombine = true },
    IndentBlanklineSpaceCharBlankline = { fg = p.comment, nocombine = true },
    IndentBlanklineContextChar        = { fg = p.green,   nocombine = true },
    IndentBlanklineContextStart       = { sp = p.green,   underline = true },
    IblIndent                         = { fg = p.comment, nocombine = true },
    IblWhitespace                     = { fg = p.comment, nocombine = true },
    IblScope                          = { fg = p.green,   nocombine = true },

    -- Which-key
    WhichKey          = { fg = p.fg },
    WhichKeyGroup     = { fg = p.green },
    WhichKeyDesc      = { fg = p.fg },
    WhichKeySeparator = { fg = p.comment },
    WhichKeyFloat     = { bg = bg_float },
    WhichKeyBorder    = { fg = p.comment, bg = bg_float },
    WhichKeyValue     = { fg = p.string },

    -- Lazy.nvim
    LazyButton           = { fg = p.fg,      bg = p.ui_bg },
    LazyButtonActive     = { fg = p.bg,      bg = p.green,   bold = true },
    LazyComment          = { fg = p.comment },
    LazyCommit           = { fg = p.green },
    LazyCommitIssue      = { fg = p.warning },
    LazyCommitType       = { fg = p.string },
    LazyDimmed           = { fg = p.comment },
    LazyDir              = { fg = p.string },
    LazyH1               = { fg = p.bg,      bg = p.green,   bold = true },
    LazyH2               = { fg = p.green,   bold = true },
    LazyNoCond           = { fg = p.error },
    LazyNormal           = { fg = p.fg,      bg = bg_float },
    LazyProgressDone     = { fg = p.green },
    LazyProgressTodo     = { fg = p.comment },
    LazyProp             = { fg = p.comment },
    LazyReasonCmd        = { fg = p.fg },
    LazyReasonEvent      = { fg = p.warning },
    LazyReasonFt         = { fg = p.string },
    LazyReasonImport     = { fg = p.green },
    LazyReasonKeys       = { fg = p.green },
    LazyReasonPlugin     = { fg = p.string },
    LazyReasonRuntime    = { fg = p.fg },
    LazyReasonSource     = { fg = p.green },
    LazyReasonStart      = { fg = p.fg },
    LazySpecial          = { fg = p.string },
    LazyTaskError        = { fg = p.error },
    LazyTaskOutput       = { fg = p.fg },
    LazyUrl              = { fg = p.string, underline = true },
    LazyValue            = { fg = p.green },

    -- Mason
    MasonHeader                      = { fg = p.bg,      bg = p.green,   bold = true },
    MasonHeaderSecondary             = { fg = p.bg,      bg = p.string,  bold = true },
    MasonHighlight                   = { fg = p.string },
    MasonHighlightBlock              = { fg = p.bg,      bg = p.string },
    MasonHighlightBlockBold          = { fg = p.bg,      bg = p.string,  bold = true },
    MasonHighlightBlockBoldSecondary = { fg = p.bg,      bg = p.green,   bold = true },
    MasonHighlightBlockSecondary     = { fg = p.bg,      bg = p.green },
    MasonHighlightSecondary          = { fg = p.green },
    MasonMuted                       = { fg = p.comment },
    MasonMutedBlock                  = { fg = p.bg,      bg = p.comment },
    MasonMutedBlockBold              = { fg = p.bg,      bg = p.comment, bold = true },
    MasonNormal                      = { fg = p.fg,      bg = bg_float },

    -- nvim-cmp
    CmpItemAbbr              = { fg = p.fg },
    CmpItemAbbrDeprecated    = { fg = p.comment, strikethrough = true },
    CmpItemAbbrMatch         = { fg = p.green,   bold = true },
    CmpItemAbbrMatchFuzzy    = { fg = p.green,   bold = true },
    CmpItemKind              = { fg = p.string },
    CmpItemKindClass         = { fg = p.fg },
    CmpItemKindColor         = { fg = p.warning },
    CmpItemKindConstant      = { fg = p.string },
    CmpItemKindConstructor   = { fg = p.fg },
    CmpItemKindEnum          = { fg = p.fg },
    CmpItemKindEnumMember    = { fg = p.string },
    CmpItemKindEvent         = { fg = p.string },
    CmpItemKindField         = { fg = p.fg },
    CmpItemKindFile          = { fg = p.fg },
    CmpItemKindFolder        = { fg = p.green },
    CmpItemKindFunction      = { fg = p.fg,      bold = true },
    CmpItemKindInterface     = { fg = p.fg },
    CmpItemKindKeyword       = { fg = p.green,   bold = true },
    CmpItemKindMethod        = { fg = p.fg,      bold = true },
    CmpItemKindModule        = { fg = p.fg },
    CmpItemKindOperator      = { fg = p.fg },
    CmpItemKindProperty      = { fg = p.fg },
    CmpItemKindReference     = { fg = p.string },
    CmpItemKindSnippet       = { fg = p.fg },
    CmpItemKindStruct        = { fg = p.fg },
    CmpItemKindText          = { fg = p.fg },
    CmpItemKindTypeParameter = { fg = p.fg },
    CmpItemKindUnit          = { fg = p.string },
    CmpItemKindValue         = { fg = p.string },
    CmpItemKindVariable      = { fg = p.fg },
    CmpItemMenu              = { fg = p.comment },

    -- blink.cmp
    BlinkCmpLabel               = { fg = p.fg },
    BlinkCmpLabelDeprecated     = { fg = p.comment, strikethrough = true },
    BlinkCmpLabelMatch          = { fg = p.green,   bold = true },
    BlinkCmpKind                = { fg = p.string },
    BlinkCmpKindClass           = { fg = p.fg },
    BlinkCmpKindColor           = { fg = p.warning },
    BlinkCmpKindConstant        = { fg = p.string },
    BlinkCmpKindConstructor     = { fg = p.fg },
    BlinkCmpKindEnum            = { fg = p.fg },
    BlinkCmpKindEnumMember      = { fg = p.string },
    BlinkCmpKindEvent           = { fg = p.string },
    BlinkCmpKindField           = { fg = p.fg },
    BlinkCmpKindFile            = { fg = p.fg },
    BlinkCmpKindFolder          = { fg = p.green },
    BlinkCmpKindFunction        = { fg = p.fg,      bold = true },
    BlinkCmpKindInterface       = { fg = p.fg },
    BlinkCmpKindKeyword         = { fg = p.green,   bold = true },
    BlinkCmpKindMethod          = { fg = p.fg,      bold = true },
    BlinkCmpKindModule          = { fg = p.fg },
    BlinkCmpKindOperator        = { fg = p.fg },
    BlinkCmpKindProperty        = { fg = p.fg },
    BlinkCmpKindReference       = { fg = p.string },
    BlinkCmpKindSnippet         = { fg = p.fg },
    BlinkCmpKindStruct          = { fg = p.fg },
    BlinkCmpKindText            = { fg = p.fg },
    BlinkCmpKindTypeParameter   = { fg = p.fg },
    BlinkCmpKindUnit            = { fg = p.string },
    BlinkCmpKindValue           = { fg = p.string },
    BlinkCmpKindVariable        = { fg = p.fg },
    BlinkCmpMenu                = { fg = p.fg,      bg = bg_float },
    BlinkCmpMenuBorder          = { fg = p.comment, bg = bg_float },
    BlinkCmpMenuSelection       = { fg = p.fg,      bg = p.selection, bold = true },
    BlinkCmpDoc                 = { fg = p.fg,      bg = bg_float },
    BlinkCmpDocBorder           = { fg = p.comment, bg = bg_float },
    BlinkCmpDocSeparator        = { fg = p.comment, bg = bg_float },
    BlinkCmpSignatureHelp       = { fg = p.fg,      bg = bg_float },
    BlinkCmpSignatureHelpBorder = { fg = p.comment, bg = bg_float },
    BlinkCmpGhostText           = { fg = p.comment },

    -- nvim-notify
    NotifyERRORBorder = { fg = p.error },
    NotifyWARNBorder  = { fg = p.warning },
    NotifyINFOBorder  = { fg = p.info },
    NotifyDEBUGBorder = { fg = p.comment },
    NotifyTRACEBorder = { fg = p.info },
    NotifyERRORIcon   = { fg = p.error },
    NotifyWARNIcon    = { fg = p.warning },
    NotifyINFOIcon    = { fg = p.info },
    NotifyDEBUGIcon   = { fg = p.comment },
    NotifyTRACEIcon   = { fg = p.info },
    NotifyERRORTitle  = { fg = p.error },
    NotifyWARNTitle   = { fg = p.warning },
    NotifyINFOTitle   = { fg = p.info },
    NotifyDEBUGTitle  = { fg = p.comment },
    NotifyTRACETitle  = { fg = p.info },
    NotifyERRORBody   = { fg = p.fg },
    NotifyWARNBody    = { fg = p.fg },
    NotifyINFOBody    = { fg = p.fg },
    NotifyDEBUGBody   = { fg = p.fg },
    NotifyTRACEBody   = { fg = p.fg },

    -- Noice
    NoiceCmdline              = { fg = p.fg },
    NoiceCmdlineIcon          = { fg = p.string },
    NoiceCmdlineIconSearch    = { fg = p.fg },
    NoiceCmdlinePopup         = { fg = p.fg,      bg = bg_float },
    NoiceCmdlinePopupBorder   = { fg = p.comment, bg = bg_float },
    NoiceCmdlinePopupTitle    = { fg = p.green },
    NoiceCmdlinePrompt        = { fg = p.green },
    NoiceConfirm              = { fg = p.fg,      bg = bg_float },
    NoiceConfirmBorder        = { fg = p.comment, bg = bg_float },
    NoiceCursor               = { fg = p.bg,      bg = p.fg },
    NoiceFormatConfirm        = { fg = p.green },
    NoiceFormatConfirmDefault = { fg = p.bg,      bg = p.green },
    NoiceFormatDate           = { fg = p.comment },
    NoiceFormatEvent          = { fg = p.string },
    NoiceFormatKind           = { fg = p.string },
    NoiceFormatLevelDebug     = { fg = p.comment },
    NoiceFormatLevelError     = { fg = p.error },
    NoiceFormatLevelInfo      = { fg = p.info },
    NoiceFormatLevelOff       = { fg = p.comment },
    NoiceFormatLevelTrace     = { fg = p.info },
    NoiceFormatLevelWarn      = { fg = p.warning },
    NoiceFormatProgressDone   = { fg = p.bg,      bg = p.green },
    NoiceFormatProgressTodo   = { fg = p.fg,      bg = p.ui_bg },
    NoiceFormatTitle          = { fg = p.green },
    NoiceLspProgressClient    = { fg = p.string },
    NoiceLspProgressSpinner   = { fg = p.green },
    NoiceLspProgressTitle     = { fg = p.fg },
    NoiceMini                 = { fg = p.fg,      bg = bg },
    NoicePopup                = { fg = p.fg,      bg = bg_float },
    NoicePopupBorder          = { fg = p.comment, bg = bg_float },
    NoiceScrollbar            = { bg = p.ui_bg },
    NoiceScrollbarThumb       = { bg = p.comment },
    NoiceSplit                = { fg = p.fg,      bg = bg },
    NoiceSplitBorder          = { fg = p.comment, bg = bg },
    NoiceVirtualText          = { fg = p.string },

    -- Trouble
    TroubleNormal           = { fg = p.fg,      bg = bg },
    TroubleCount            = { fg = p.bg,      bg = p.green,   bold = true },
    TroubleText             = { fg = p.fg },
    TroublePreview          = { bg = p.selection },
    TroubleSource           = { fg = p.comment },
    TroubleCode             = { fg = p.comment },
    TroublePos              = { fg = p.comment },
    TroubleLocation         = { fg = p.comment },
    TroubleIndent           = { fg = p.comment },
    TroubleFoldIcon         = { fg = p.string },
    TroubleFilename         = { fg = p.green },
    TroubleIndentFoldClosed = { fg = p.fg },
    TroubleSignError        = { fg = p.error },
    TroubleSignWarning      = { fg = p.warning },
    TroubleSignInformation  = { fg = p.info },
    TroubleSignHint         = { fg = p.hint },

    -- Flash
    FlashBackdrop = { fg = p.comment },
    FlashMatch    = { fg = p.fg,   bg = p.selection },
    FlashCurrent  = { fg = p.fg,   bg = p.ui_bg },
    FlashLabel    = { fg = p.bg,   bg = p.green, bold = true },
    FlashCursor   = { link = "Cursor" },

    -- Leap
    LeapMatch          = { fg = p.fg,  bg = p.selection, bold = true },
    LeapLabelPrimary   = { fg = p.bg,  bg = p.green,     bold = true },
    LeapLabelSecondary = { fg = p.bg,  bg = p.string,    bold = true },
    LeapBackdrop       = { fg = p.comment },

    -- Mini
    MiniCompletionActiveParameter = { underline = true },
    MiniCursorword                = { bg = p.selection },
    MiniCursorwordCurrent         = { bg = p.selection },
    MiniIndentscopeSymbol         = { fg = p.green },
    MiniIndentscopePrefix         = { nocombine = true },
    MiniJump                      = { fg = p.bg,      bg = p.green },
    MiniJump2dSpot                = { fg = p.green,   bold = true },
    MiniStarterCurrent            = {},
    MiniStarterFooter             = { fg = p.comment },
    MiniStarterHeader             = { fg = p.green },
    MiniStarterInactive           = { fg = p.comment },
    MiniStarterItem               = { fg = p.fg },
    MiniStarterItemBullet         = { fg = p.fg },
    MiniStarterItemPrefix         = { fg = p.fg },
    MiniStarterSection            = { fg = p.string },
    MiniStarterQuery              = { fg = p.warning },
    MiniStatuslineDevinfo         = { fg = p.fg,      bg = p.selection },
    MiniStatuslineFileinfo        = { fg = p.fg,      bg = p.selection },
    MiniStatuslineFilename        = { fg = p.fg,      bg = p.ui_bg },
    MiniStatuslineInactive        = { fg = p.comment, bg = p.ui_bg },
    MiniStatuslineModeCommand     = { fg = p.bg,      bg = p.fg,      bold = true },
    MiniStatuslineModeInsert      = { fg = p.bg,      bg = p.green,   bold = true },
    MiniStatuslineModeNormal      = { fg = p.bg,      bg = p.green,   bold = true },
    MiniStatuslineModeOther       = { fg = p.bg,      bg = p.string,  bold = true },
    MiniStatuslineModeReplace     = { fg = p.bg,      bg = p.error,   bold = true },
    MiniStatuslineModeVisual      = { fg = p.bg,      bg = p.warning, bold = true },
    MiniSurround                  = { fg = p.bg,      bg = p.warning },
    MiniTablineCurrent            = { fg = p.fg,      bg = p.bg,      bold = true },
    MiniTablineFill               = { bg = p.ui_bg },
    MiniTablineHidden             = { fg = p.fg,      bg = p.ui_bg },
    MiniTablineModifiedCurrent    = { fg = p.green,   bg = p.bg },
    MiniTablineModifiedHidden     = { fg = p.green,   bg = p.ui_bg },
    MiniTablineModifiedVisible    = { fg = p.green,   bg = p.ui_bg },
    MiniTablineTabpagesection     = { fg = p.fg,      bg = p.selection },
    MiniTablineVisible            = { fg = p.fg,      bg = p.ui_bg },
    MiniTestEmphasis              = { bold = true },
    MiniTestFail                  = { fg = p.error,   bold = true },
    MiniTestPass                  = { fg = p.green,   bold = true },
    MiniTrailspace                = { bg = p.error },

    -- Nvim-navic
    NavicIconsFile          = { fg = p.fg },
    NavicIconsModule        = { fg = p.string },
    NavicIconsNamespace     = { fg = p.string },
    NavicIconsPackage       = { fg = p.string },
    NavicIconsClass         = { fg = p.fg },
    NavicIconsMethod        = { fg = p.fg,      bold = true },
    NavicIconsProperty      = { fg = p.fg },
    NavicIconsField         = { fg = p.fg },
    NavicIconsConstructor   = { fg = p.fg },
    NavicIconsEnum          = { fg = p.fg },
    NavicIconsInterface     = { fg = p.fg },
    NavicIconsFunction      = { fg = p.fg,      bold = true },
    NavicIconsVariable      = { fg = p.fg },
    NavicIconsConstant      = { fg = p.string },
    NavicIconsString        = { fg = p.string },
    NavicIconsNumber        = { fg = p.string },
    NavicIconsBoolean       = { fg = p.string },
    NavicIconsArray         = { fg = p.string },
    NavicIconsObject        = { fg = p.string },
    NavicIconsKey           = { fg = p.green },
    NavicIconsNull          = { fg = p.string },
    NavicIconsEnumMember    = { fg = p.string },
    NavicIconsStruct        = { fg = p.fg },
    NavicIconsEvent         = { fg = p.string },
    NavicIconsOperator      = { fg = p.fg },
    NavicIconsTypeParameter = { fg = p.fg },
    NavicText               = { fg = p.fg },
    NavicSeparator          = { fg = p.comment },

    -- Bufferline
    BufferLineFill                      = { bg = bg },
    BufferLineBackground                = { fg = p.comment, bg = p.ui_bg },
    BufferLineBuffer                    = { fg = p.comment, bg = p.ui_bg },
    BufferLineBufferVisible             = { fg = p.fg,      bg = p.bg },
    BufferLineBufferSelected            = { fg = p.fg,      bg = p.bg,     bold = true },
    BufferLineTab                       = { fg = p.comment, bg = p.ui_bg },
    BufferLineTabSelected               = { fg = p.green,   bg = p.bg,     bold = true },
    BufferLineTabClose                  = { fg = p.error,   bg = p.ui_bg },
    BufferLineTabSeparator              = { fg = bg,        bg = p.ui_bg },
    BufferLineTabSeparatorSelected      = { fg = bg,        bg = p.bg },
    BufferLineIndicatorSelected         = { fg = p.green,   bg = p.bg },
    BufferLineIndicatorVisible          = { fg = p.bg,      bg = p.bg },
    BufferLineSeparator                 = { fg = bg,        bg = p.ui_bg },
    BufferLineSeparatorVisible          = { fg = bg,        bg = p.bg },
    BufferLineSeparatorSelected         = { fg = bg,        bg = p.bg },
    BufferLineCloseButton               = { fg = p.comment, bg = p.ui_bg },
    BufferLineCloseButtonVisible        = { fg = p.fg,      bg = p.bg },
    BufferLineCloseButtonSelected       = { fg = p.error,   bg = p.bg },
    BufferLineModified                  = { fg = p.green,   bg = p.ui_bg },
    BufferLineModifiedVisible           = { fg = p.green,   bg = p.bg },
    BufferLineModifiedSelected          = { fg = p.green,   bg = p.bg },
    BufferLineDuplicate                 = { fg = p.comment, bg = p.ui_bg, italic = true },
    BufferLineDuplicateVisible          = { fg = p.comment, bg = p.bg,   italic = true },
    BufferLineDuplicateSelected         = { fg = p.comment, bg = p.bg,   italic = true },
    BufferLinePick                      = { fg = p.green,   bg = p.ui_bg, bold = true },
    BufferLinePickVisible               = { fg = p.green,   bg = p.bg,   bold = true },
    BufferLinePickSelected              = { fg = p.green,   bg = p.bg,   bold = true },
    BufferLineDiagnostic                = { fg = p.comment, bg = p.ui_bg },
    BufferLineDiagnosticVisible         = { fg = p.comment, bg = p.bg },
    BufferLineDiagnosticSelected        = { fg = p.fg,      bg = p.bg },
    BufferLineError                     = { fg = p.error,   bg = p.ui_bg },
    BufferLineErrorVisible              = { fg = p.error,   bg = p.bg },
    BufferLineErrorSelected             = { fg = p.error,   bg = p.bg },
    BufferLineErrorDiagnostic           = { fg = p.error,   bg = p.ui_bg },
    BufferLineErrorDiagnosticVisible    = { fg = p.error,   bg = p.bg },
    BufferLineErrorDiagnosticSelected   = { fg = p.error,   bg = p.bg },
    BufferLineWarning                   = { fg = p.warning, bg = p.ui_bg },
    BufferLineWarningVisible            = { fg = p.warning, bg = p.bg },
    BufferLineWarningSelected           = { fg = p.warning, bg = p.bg },
    BufferLineWarningDiagnostic         = { fg = p.warning, bg = p.ui_bg },
    BufferLineWarningDiagnosticVisible  = { fg = p.warning, bg = p.bg },
    BufferLineWarningDiagnosticSelected = { fg = p.warning, bg = p.bg },
    BufferLineInfo                      = { fg = p.info,    bg = p.ui_bg },
    BufferLineInfoVisible               = { fg = p.info,    bg = p.bg },
    BufferLineInfoSelected              = { fg = p.info,    bg = p.bg },
    BufferLineInfoDiagnostic            = { fg = p.info,    bg = p.ui_bg },
    BufferLineInfoDiagnosticVisible     = { fg = p.info,    bg = p.bg },
    BufferLineInfoDiagnosticSelected    = { fg = p.info,    bg = p.bg },
    BufferLineHint                      = { fg = p.hint,    bg = p.ui_bg },
    BufferLineHintVisible               = { fg = p.hint,    bg = p.bg },
    BufferLineHintSelected              = { fg = p.hint,    bg = p.bg },
    BufferLineHintDiagnostic            = { fg = p.hint,    bg = p.ui_bg },
    BufferLineHintDiagnosticVisible     = { fg = p.hint,    bg = p.bg },
    BufferLineHintDiagnosticSelected    = { fg = p.hint,    bg = p.bg },
    BufferLineNumbers                   = { fg = p.comment, bg = p.ui_bg },
    BufferLineNumbersVisible            = { fg = p.fg,      bg = p.bg },
    BufferLineNumbersSelected           = { fg = p.green,   bg = p.bg,    bold = true },
    BufferLineGroupSeparator            = { fg = p.comment, bg = bg },
    BufferLineGroupLabel                = { fg = p.bg,      bg = p.green, bold = true },
    BufferLineOffsetSeparator           = { fg = p.comment, bg = p.bg },
    BufferLineTruncMarker               = { fg = p.comment, bg = bg },

    -- Dashboard
    DashboardHeader   = { fg = p.green },
    DashboardCenter   = { fg = p.string },
    DashboardFooter   = { fg = p.comment },
    DashboardShortCut = { fg = p.fg },

    -- Alpha
    AlphaHeader   = { fg = p.green },
    AlphaButtons  = { fg = p.string },
    AlphaShortcut = { fg = p.fg },
    AlphaFooter   = { fg = p.comment },

    -- Snacks
    SnacksNormal                 = { fg = p.fg,      bg = bg_float },
    SnacksDashboardNormal        = { fg = p.fg,      bg = bg },
    SnacksDashboardDesc          = { fg = p.string },
    SnacksDashboardFile          = { fg = p.fg },
    SnacksDashboardDir           = { fg = p.comment },
    SnacksDashboardFooter        = { fg = p.comment },
    SnacksDashboardHeader        = { fg = p.green },
    SnacksDashboardIcon          = { fg = p.green },
    SnacksDashboardKey           = { fg = p.fg,      bold = true },
    SnacksDashboardSpecial       = { fg = p.green },
    SnacksDashboardTitle         = { fg = p.green,   bold = true },
    SnacksNotifierError          = { fg = p.error },
    SnacksNotifierWarn           = { fg = p.warning },
    SnacksNotifierInfo           = { fg = p.info },
    SnacksNotifierDebug          = { fg = p.comment },
    SnacksNotifierTrace          = { fg = p.info },
    SnacksNotifierIconError      = { fg = p.error },
    SnacksNotifierIconWarn       = { fg = p.warning },
    SnacksNotifierIconInfo       = { fg = p.info },
    SnacksNotifierIconDebug      = { fg = p.comment },
    SnacksNotifierIconTrace      = { fg = p.info },
    SnacksNotifierTitleError     = { fg = p.error },
    SnacksNotifierTitleWarn      = { fg = p.warning },
    SnacksNotifierTitleInfo      = { fg = p.info },
    SnacksNotifierTitleDebug     = { fg = p.comment },
    SnacksNotifierTitleTrace     = { fg = p.info },
    SnacksNotifierBorderError    = { fg = p.error },
    SnacksNotifierBorderWarn     = { fg = p.warning },
    SnacksNotifierBorderInfo     = { fg = p.info },
    SnacksNotifierBorderDebug    = { fg = p.comment },
    SnacksNotifierBorderTrace    = { fg = p.info },
    SnacksIndent                 = { fg = p.comment },
    SnacksIndentScope            = { fg = p.green },
    SnacksPickerMatch            = { fg = p.green,   bold = true },
    SnacksPickerPrompt           = { fg = p.green },
    SnacksPickerDir              = { fg = p.comment },
    SnacksPickerFile             = { fg = p.fg },
    SnacksPickerDirectory        = { fg = p.green },
    SnacksPickerTitle            = { fg = p.green,   bold = true },
    SnacksPickerBorder           = { fg = p.comment },
    SnacksPickerSelection        = { bg = p.selection },
    SnacksPickerSelectionCaret   = { fg = p.green,   bg = p.selection },
    SnacksInputIcon              = { fg = p.green },
    SnacksInputBorder            = { fg = p.comment },
    SnacksInputTitle             = { fg = p.green },
    SnacksDim                    = { fg = p.comment },
    SnacksScratchKey             = { fg = p.warning },
    SnacksScratchDesc            = { fg = p.string },
    SnacksProfilerIconInfo       = { fg = p.info },
    SnacksProfilerBadge          = { fg = p.bg,      bg = p.string },
  }
end

return { get = get }
