# vim:ft=kitty
## name: vault

background            #0a0a00
foreground           #c8b400
cursor               #c8b400
cursor_text_color    #0a0a00
selection_background #2a3a00
selection_foreground #c8b400

# black
color0  #0a0a00
color8  #2a2800
# red
color1  #cc4400
color9  #cc4400
# green
color2  #00ff41
color10 #7aff00
# yellow
color3  #c8b400
color11 #c8b400
# blue
color4  #5a5200
color12 #5a5200
# magenta
color5  #5a5200
color13 #5a5200
# cyan
color6  #7aff00
color14 #00ff41
# white
color7  #c8b400
color15 #e8d400

# tab bar
active_tab_foreground   #0a0a00
active_tab_background    #c8b400
inactive_tab_foreground #5a5200
inactive_tab_background #0a0a00
tab_bar_background      #0a0a00
tab_bar_margin_color    #0a0a00

